version: "3.5"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=jenkinsdb
    networks:
      - net1

  web:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - net1
    links:
      - db
    depends_on:
      - db
networks:
  net1: